export { default as Benifits } from "./Benifits";
export { default as Company } from "./Company";
export { default as Contact } from "./Contact";
export { default as Features } from "./Features";
export { default as Footer } from "./Footer";
export { default as Hero } from "./Hero";
export { default as Navbar } from "./Navbar";
export { default as PartnersSupport } from "./PartnersSupport";
export { default as Plans } from "./Plans";
